#!/bin/zsh
setopt NULL_GLOB

file="$1"

if [[ -z "$file" ]]; then
  echo "Usage: replace <filename>"
  exit 1
fi

# If file exists, rotate it
if [[ -f "$file" ]]; then
  # Find highest existing version
  max=0
  for f in ${file}-V*; do
    [[ -e "$f" ]] || continue
    num=${f##*-V}
    if [[ "$num" =~ '^[0-9]+$' ]]; then
      (( num > max )) && max=$num
    fi
  done

  next=$((max + 1))
  new=$(printf "%s-V%03d" "$file" "$next")
  mv "$file" "$new"
  echo "Moved existing file to: $new"
fi

# Write clipboard into the file
pbpaste > "$file"
echo "Created new file: $file"

